//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeGP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeGP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;crossover strategy=&quot;subtree&quot;&gt;
        ///
        ///&lt;strategy name=&quot;subtree&quot; &gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;/crossover&gt;.
        /// </summary>
        internal static string CrossoverInstructionFactory {
            get {
                return ResourceManager.GetString("CrossoverInstructionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;pop_mutate strategy=&quot;macro_mutation&quot; &gt;
        ///
        ///&lt;strategy name=&quot;macro_mutation&quot;&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;/pop_mutate&gt;.
        /// </summary>
        internal static string MutationInstructionFactory {
            get {
                return ResourceManager.GetString("MutationInstructionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;pop_init strategy=&quot;variable&quot;&gt;
        ///
        ///&lt;strategy name=&quot;variable&quot;&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;strategy name=&quot;ramped_variable&quot;&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;strategy name=&quot;grow&quot;&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;/pop_init&gt;.
        /// </summary>
        internal static string PopInitInstructionFactory {
            get {
                return ResourceManager.GetString("PopInitInstructionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;selection_config strategy=&quot;tournament&quot;&gt;
        ///
        ///&lt;strategy name=&quot;tournament&quot;&gt;
        ///&lt;param name=&quot;tournament_size&quot; value=&quot;2&quot; /&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;/selection_config&gt;.
        /// </summary>
        internal static string ReproductionSelectionInstructionFactory {
            get {
                return ResourceManager.GetString("ReproductionSelectionInstructionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;survival_instruction strategy=&quot;probablistic&quot; &gt;
        ///
        ///&lt;strategy name=&quot;probablistic&quot; &gt;
        ///&lt;param name=&quot;reproduction_probability&quot; value=&quot;1&quot; /&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;strategy name=&quot;compete&quot; &gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;/survival_instruction&gt;.
        /// </summary>
        internal static string SurvivalInstructionFactory {
            get {
                return ResourceManager.GetString("SurvivalInstructionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;configuration&gt;
        ///&lt;parameters&gt;
        ///&lt;param name=&quot;NumRegisters&quot; value=&quot;6&quot; /&gt;
        ///&lt;param name=&quot;PopulationSize&quot; value=&quot;1000&quot; /&gt;
        ///&lt;param name=&quot;Epsilon&quot; value=&quot;0.000000001&quot; /&gt;
        ///&lt;param name=&quot;MaxGenerations&quot; value=&quot;100&quot; /&gt;
        ///&lt;param name=&quot;Maximization&quot; value=&quot;false&quot; /&gt;
        ///&lt;param name=&quot;CrossoverRate&quot; value=&quot;0.9&quot; /&gt;
        ///&lt;param name=&quot;MacroMutationRate&quot; value=&quot;0.005&quot; /&gt;
        ///&lt;param name=&quot;MicroMutationRate&quot; value=&quot;0.005&quot; /&gt;
        ///&lt;param name=&quot;ReproductionRate&quot; value=&quot;0.09&quot; /&gt;
        ///&lt;param name=&quot;MaxDepthForCrossover&quot; value [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TGPConfig {
            get {
                return ResourceManager.GetString("TGPConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;protected_definition&gt;
        ///
        ///&lt;C_undef use=&quot;low&quot;&gt;
        ///&lt;param name=&quot;low&quot; value=&quot;1&quot; /&gt;
        ///&lt;param name=&quot;high&quot; value=&quot;1000000&quot; /&gt;
        ///&lt;/C_undef&gt;
        ///
        ///&lt;LGP_REG_POSITIVE_INF value=&quot;10000000&quot; /&gt;
        ///&lt;LGP_REG_NEGATIVE_INF value=&quot;-10000000&quot; /&gt;
        ///
        ///&lt;/protected_definition&gt;.
        /// </summary>
        internal static string TGPUndefined {
            get {
                return ResourceManager.GetString("TGPUndefined", resourceCulture);
            }
        }
    }
}
